<?php declare(strict_types=1);

/**
 * Example demonstrating Part 2 of Batch Processing: RETRIEVAL.
 * - Takes a Batch ID as input (e.g., from command line).
 * - Retrieves the status of the batch job.
 * - If completed, fetches and displays the results.
 * - If failed, displays error information.
 *
 * NOTE: Run this script AFTER batch-submit.php has successfully submitted a job
 *       and you have waited for the provider to process it.
 */

require __DIR__ . '/bootstrap.php';

use AIAccess\Batch\Status;
use AIAccess\Provider;
use AIAccess\ServiceException;


// --- 1. GET BATCH ID AND PROVIDER ---

// Determine the Batch ID to retrieve.
// Priority: Command-line argument > Hardcoded placeholder
$batchId = $argv[1] ?? null; // Get from first command-line argument

if (!$batchId) {
	echo "Error: Batch ID is required.\n";
	echo "Please provide the Batch ID generated by 'batch-submit.php' as a command-line argument.\n";
	echo "Example: php examples/batch-retrieve.php 'batch_abc123xyz'\n";
	exit(1);
}

// This example assumes it based on the ID prefix, which is specific to OpenAI batches ('batch_...').
// For Claude ('batch_run_...'), you'd need to adjust this or pass the provider as another argument.
// A more robust solution in a real application would store the provider alongside the batch ID.
if (str_starts_with($batchId, 'batch_run_')) {
	$provider = 'claude';
} elseif (str_starts_with($batchId, 'batch_')) {
	$provider = 'openai';
} else {
	// Default or guess - might need user input or better logic
	$provider = 'openai'; // Default guess
	echo "Warning: Could not determine provider from Batch ID prefix. Assuming '$provider'.\n";
	echo "If this is incorrect, please modify the script or use a more robust method to track the provider.\n";
}


echo "Attempting to retrieve Batch ID: $batchId\n";
echo "Using Provider: $provider\n";


// --- 2. CREATE THE CLIENT --- (Must match the provider used for submission)

$apiKey = loadApiKey(__DIR__ . "/{$provider}.key.txt");
$client = match ($provider) {
	'openai' => new Provider\OpenAI\Client($apiKey),
	'claude' => new Provider\Claude\Client($apiKey),
	default => throw new LogicException("Provider '$provider' is not configured or does not support Batch API retrieval."),
};

echo 'Client created for: ' . $client::class . "\n\n";


// --- 3. RETRIEVE AND PROCESS BATCH STATUS/RESULTS ---

try {
	// Retrieve the current state of the batch job from the provider
	echo "Retrieving batch details...\n";
	$batchResponse = $client->retrieveBatch($batchId);

	$status = $batchResponse->getStatus();
	echo 'Current Batch Status: ' . $status->name . "\n";

	// Handle based on status
	switch ($status) {
		case Status::Completed:
			echo "\n--- Batch Completed ---\n";
			echo "Fetching results...\n";

			// Get the results, which is an array mapping custom_id => Message object
			$messages = $batchResponse->getMessages(); // This might involve another API call internally

			if ($messages === null) {
				echo "Results file is not available or could not be fetched/parsed.\n";
				echo "Raw Batch Data:\n" . print_r($batchResponse->getRawResult(), true);

			} elseif (empty($messages)) {
				echo "Batch completed, but no messages were successfully processed or returned.\n";

			} else {
				echo 'Retrieved ' . count($messages) . " results:\n\n";
				foreach ($messages as $customId => $message) {
					echo "--- Result for Custom ID: '$customId' ---\n";
					echo trim($message->getText()) . "\n";
					echo "------------------------------------------\n\n";
				}
			}
			break;

		case Status::Failed:
			echo "\n--- Batch Failed ---\n";
			$error = $batchResponse->getError();
			echo 'Error Details: ' . ($error ?? 'No specific error message provided.') . "\n";
			// You might want to log the full raw response for debugging
			// echo "\nRaw Batch Data:\n" . print_r($batchResponse->getRawResult(), true);
			break;

		case Status::InProgress:
			echo "\nBatch is still processing. Please try retrieving again later.\n";
			break;

		case Status::Other:
		default:
			echo "\nBatch is in an unexpected or intermediate state ('" . $status->name . "').\n";
			echo 'Raw Status from API: ' . ($batchResponse->getRawResult()['status'] ?? 'N/A') . "\n"; // Example for OpenAI
			echo "Check again later or consult provider documentation.\n";
			break;
	}

	// Optionally display timing information if available
	$createdAt = $batchResponse->getCreatedAt();
	$completedAt = $batchResponse->getCompletedAt();
	if ($createdAt) {
		echo "\nCreated At: " . $createdAt->format(DateTime::RFC3339) . "\n";
	}
	if ($completedAt) {
		echo 'Completed/Ended At: ' . $completedAt->format(DateTime::RFC3339) . "\n";
	}


} catch (ServiceException $e) {
	echo "\nError retrieving batch details: [" . $e::class . '] ' . $e->getMessage() . "\n";
	// Specific handling for "Not Found" errors
	if ($e instanceof AIAccess\ApiException && $e->getCode() === 404) {
		echo "Ensure the Batch ID '$batchId' is correct and belongs to the selected provider ('$provider').\n";
	}
}
